#!/usr/bin/env python3

# dump_raw.py: Simple utility to parse and display raw UDP dump files
#              generated by capture_pedestal_events.py.

import sys
import struct

MAGIC = 0x4445504f42415551 # "QUABOPED"

def dump_raw(filename):
    try:
        with open(filename, 'rb') as f:
            while True:
                # Read fixed part of the header: magic(8), tv_sec(8), tv_nsec(8), host_len(2)
                header_data = f.read(26)
                if not header_data:
                    break
                
                if len(header_data) < 26:
                    print(f"Warning: Truncated header at end of file.", file=sys.stderr)
                    break
                
                magic, tv_sec, tv_nsec, host_len = struct.unpack('<QQQH', header_data)
                
                if magic != MAGIC:
                    print(f"Error: Invalid magic number 0x{magic:016x} at offset {f.tell()-26}", file=sys.stderr)
                    # Attempt to resync or stop
                    break
                
                # Decode magic number to ASCII for display
                magic_str = struct.pack('<Q', magic).decode('ascii', errors='replace')
                
                # Read host string
                host_bytes = f.read(host_len)
                host = host_bytes.decode('utf-8')
                
                # Read port(2) and data_len(4)
                metadata = f.read(6)
                port, data_len = struct.unpack('<HI', metadata)
                
                # Read raw data
                data = f.read(data_len)
                
                # Extract first 20 bytes as 10 unsigned shorts (H)
                # Note: Quabo data is typically little-endian for the pixels themselves
                num_vals = min(10, data_len // 2)
                vals = struct.unpack(f'<{num_vals}H', data[:num_vals*2])
                vals_str = " ".join(f"{v:5d}" for v in vals)
                
                print(f"{magic_str:8s} {host:15s} {port:5d} {tv_sec:10d} {tv_nsec:09d} {data_len:5d} {vals_str}")
                
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.", file=sys.stderr)
    except BrokenPipeError:
        # Standard behavior for piping to 'head': exit silently
        sys.stdout.flush()
        sys.stderr.close()
        sys.exit(0)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <raw_dump_file>")
        sys.exit(1)
    
    dump_raw(sys.argv[1])
